#pragma once


enum player_input_command_t
{
   PLAYER_INPUT_COMMAND_UNDEF = 0,
   PLAYER_INPUT_COMMAND_UP,
   PLAYER_INPUT_COMMAND_DOWN,
   PLAYER_INPUT_COMMAND_LEFT,
   PLAYER_INPUT_COMMAND_RIGHT,
   PLAYER_INPUT_COMMAND_START,
   PLAYER_INPUT_COMMAND_BACK,
   PLAYER_INPUT_COMMAND_A,
   PLAYER_INPUT_COMMAND_B,
   PLAYER_INPUT_COMMAND_C,
   PLAYER_INPUT_COMMAND_SIZE_MAX,
};


